name: food_recognizer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  auto_size_text: ^3.0.0
  dio: ^5.3.2
  firebase_core: ^2.15.1
  google_mlkit_text_recognition: ^0.10.0
  google_mlkit_commons: ^0.5.0  
  google_mlkit_translation: ^0.8.0
  camera: ^0.10.5+4
  path_provider: ^2.1.1
  path: ^1.8.3
  image_picker: ^1.0.4
  camerawesome: ^1.4.0
  ffi: ^2.1.0
  better_open_file: ^3.6.4
  google_mlkit_language_id: ^0.8.0
  provider: ^6.0.5
  # google_ml_kit: ^0.16.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: ClashGrotesk
      fonts:
        - asset: assets/fonts/ClashGrotesk-Regular.otf
